title: Maak een patrouillerend GameObject
hero_image: images/banner.png
description: Maak een patrouillerend GameObject
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - 
    title: Maak een patrouillerend GameObject
