title: Create a patrolling GameObject
hero_image: images/banner.png
description: Create a patrolling GameObject
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - title: Create a patrolling GameObject
