---
title: Créer un GameObject patrouilleur
hero_image: images/banner.png
description: Créer un GameObject patrouilleur
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - title: Créer un GameObject patrouilleur
